improving docs for v0.3
pietroppeter/nimib pull request #103
Opened 2022-07-03 13:46 UTC by pietroppeter

- make sure all changes (recent and older) are documented
- improve changelog

2022-07-10 16:45 UTC, pietroppeter commented
ok, this is done. After this is merged I would tag and release.
@HugoGranstrom would you give it a look?

some small details:
- I did not document `nbClearOutput` because I cannot remember what was its use case.
- I removed random from import (I think it was used in js code generation but now it should not be anymore needed)
- I am not sure if it is worth adding at the end of nimib.nim a pragma to turn off unusedImport warning (a normal run of index.nim would still mark sequtils and strutils as not used). I also found very little documentation of this, basically only https://forum.nim-lang.org/t/5461#34187

2022-07-10 16:59 UTC, HugoGranstrom commented
> ok, this is done. After this is merged I would tag and release.
> @HugoGranstrom would you give it a look?

:confetti_ball: 
I'll take a closer look later tonight but I'll answer your questions:

> I did not document nbClearOutput because I cannot remember what was its use case.

It was mainly for nimiSlides to save some screen estate if the output of the code block wasn't important. (ggplotnim for example echo:ed some really noisy stuff for example)

> I removed random from import (I think it was used in js code generation but now it should not be anymore needed)

Ah yes forgot about that one. Also I saw that they have released a new Karax release so we should be able to drop the `@#head` in the `nimib.nimble` file.

> I am not sure if it is worth adding at the end of nimib.nim a pragma to turn off unusedImport warning (a normal run of index.nim would still mark sequtils and strutils as not used). I also found very little documentation of this, basically only https://forum.nim-lang.org/t/5461#34187

As long as it doesn't affect the user's imports, I think that would be a welcome addition :+1:

2022-07-10 17:23 UTC, pietroppeter commented
> > I did not document nbClearOutput because I cannot remember what was its use case.
> 
> It was mainly for nimiSlides to save some screen estate if the output of the code block wasn't important. (ggplotnim for example echo:ed some really noisy stuff for example)

ok, makes sense. added explanation.

> > I removed random from import (I think it was used in js code generation but now it should not be anymore needed)
> 
> Ah yes forgot about that one. Also I saw that they have released a new Karax release so we should be able to drop the `@#head` in the `nimib.nimble` file.

also update Karax version

> > I am not sure if it is worth adding at the end of nimib.nim a pragma to turn off unusedImport warning (a normal run of index.nim would still mark sequtils and strutils as not used). I also found very little documentation of this, basically only https://forum.nim-lang.org/t/5461#34187
> 
> As long as it doesn't affect the user's imports, I think that would be a welcome addition 👍

good idea. I checked and indeed it does not affect user's imports. Apparently it only affects import of the module where it is added. So added.

Instead I am having issues with the markdown backend. I did not realize it is actually using parts of html backend and not sure why... will look into that and fix it.

2022-07-10 18:02 UTC, HugoGranstrom requested changes
Nothing major really, just a few nitpicks. It looks very good :rocket: 

But wow! There has been so much happening to nimib over the last year, I can't believe it was just over a year since v0.1 was released :exploding_head:

2022-07-10 18:14 UTC, pietroppeter commented on docsrc/index.nim
> +  Example blocks created with `newNbSlimBlock` are `nbText`, `nbImage` and `nbFile`.
you are right, will remove the ref to nbFile

2022-07-10 18:17 UTC, pietroppeter commented on changelog.md
> +* untyped version of `nbFile` removed, new example document `files.nim`, changed the rendering of `nbFile`
indeed I do not know it it was removed at some point or not (I already forgot if I added it back in some previous PR)

2022-07-10 18:20 UTC, pietroppeter commented
> But wow! There has been so much happening to nimib over the last year, I can't believe it was just over a year since v0.1 was released 🤯

indeed when writing the history/changelog I was also surprised by how many changes there were!

fixed your remarks and also fixed the markdown backend which required some non trivial changes. Also updated the rendering documentation which was indeed obsolete.

2022-07-10 18:21 UTC, HugoGranstrom approved these changes

2022-07-10 18:25 UTC, HugoGranstrom commented
> fixed your remarks and also fixed the markdown backend which required some non trivial changes. Also updated the rendering documentation which was indeed obsolete.

:rocket: :partying_face: Awesome! It felt very typical that it was the thing we will refactor next that was misbehaving, I'll take that as a sign :rofl: 

So all that's left now is to go through the preview one more time and then release 0.3? :exploding_head:

2022-07-10 18:28 UTC, pietroppeter commented
> So all that's left now is to go through the preview one more time and then release 0.3? 🤯

Yep! I will also do another review later on

2022-07-10 18:37 UTC, HugoGranstrom commented on docsrc/index.nim
>    docs = if defined(useMdBackend): "https://pietroppeter.github.io/nimib" else: "."
```suggestion
  docs = if defined(mdOutput): "https://pietroppeter.github.io/nimib" else: "."
```
The readme links were incorrect

2022-07-11 10:33 UTC, merged

2022-07-11 10:34 UTC, pietroppeter commented
made another pass but seems good to go! 🥳

2022-07-11 14:20 UTC, pietroppeter commented
you are right, will do