Fix compile error when using custom nimble env (#216)
pietroppeter/nimib pull request #217
Opened 2023-08-19 07:02 UTC by sent44

Fix #216

Tell me if you don't want regex

2023-10-29 23:28 UTC, pietroppeter requested changes

2023-10-29 23:28 UTC, pietroppeter commented on src/nimib/config.nim
> +  let dumpedJson = execProcess("nimble dump", dir)
```suggestion
  let dumpedJson = execProcess("nimble dump --json --silent", dir) 
```

using just this change and removing all other changes should be a better fix

2023-10-29 23:29 UTC, pietroppeter commented
hi, thanks for working on this!

As mentioned here https://github.com/pietroppeter/nimib/issues/216#issuecomment-1784271686 a better fix is just to use the `--silent` option. I added a suggestion for the line to be changed and the rest of changes should be discarded

2025-06-13 15:27 UTC, closed without merging

2025-06-13 15:27 UTC, sent44 commented
Fixed by #230 
I was busy at that time and then forgot about this.